---
- name: Deploy MQTT Broker (Mosquitto)
  hosts: all
  become: yes
  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Mosquitto broker and client
      ansible.builtin.apt:
        name:
          - mosquitto
          - mosquitto-clients
        state: present

    - name: Ensure Mosquitto service is enabled and running
      ansible.builtin.service:
        name: mosquitto
        state: started
        enabled: yes

    - name: Open MQTT port 1883 via ufw
      ansible.builtin.command: ufw allow 1883/tcp
      become: yes
      ignore_errors: yes   # in case ufw is not installed
